# Generated by Django 5.1.1 on 2024-09-11 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectPApp', '0002_rename_persona_cliente_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email del cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectPApp.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(verbose_name='Fecha del pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total del pedido'),
        ),
    ]
