# Generated by Django 5.1.1 on 2024-09-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Producto disponible'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Foto del producto'),
        ),
    ]
